MODEL:
  PRETRAIN_CHOICE: 'imagenet'
  RES_USE : 0
  TRANS_USE : 1
  PRETRAIN_PATH_T : '/15127306268/wyh/UIS/pth/restv2_large_224.pth'
  TRANSFORMER_TYPE : 'restv2_large'


INPUT:
  SIZE_TRAIN: [256, 128]
  SIZE_TEST: [256, 128]
  PROB: 0.5 # random horizontal flip
  RE_PROB: 0.5 # random erasing
  PADDING: 10
  PIXEL_MEAN: [0.5, 0.5, 0.5]
  PIXEL_STD: [0.5, 0.5, 0.5]

DATASETS:
  NAMES: ('market1501')
  ROOT_DIR: '/15127306268/wyh/UIS/data'

TEST:
  RE_RANKING: 'no'
  WEIGHT: ''
  NECK_FEAT: 'before'
  FEAT_NORM: 'yes'

OUTPUT_DIR: './market_restv2l_128'

