MODEL:
  PRETRAIN_CHOICE: 'imagenet'
  RES_USE: 1
  TRANS_USE: 1
  DEPTH: 1
  MIX_DIM: 768
  PRETRAIN_PATH_R: '/13559197192/wyh/UNIReID/pth/r50.pth'
  PRETRAIN_PATH_T: '/13559197192/wyh/UNIReID/pth/vitb_16_224_21k.pth'
  TRANSFORMER_TYPE: 'vit_base_patch16_224'
  STRIDE_SIZE: [ 16, 16 ]
  SIE_CAMERA: True
  MIX_MODE: 0
  BASE: 0
  DIST_TRAIN: True
INPUT:
  SIZE_TRAIN: [ 256, 128 ]
  SIZE_TEST: [ 256, 128 ]
  PROB: 0.5 # random horizontal flip
  RE_PROB: 0.5 # random erasing
  PADDING: 10


DATASETS:
  NAMES: ('RGBNT201')
  ROOT_DIR: '/13559197192/wyh/UNIReID/data/'
  TRIAL: 1
DATALOADER:
  SAMPLER: 'softmax_triplet'
  NUM_INSTANCE: 2
  NUM_WORKERS : 28
SOLVER:
  OPTIMIZER_NAME: 'SGD'
  BASE_LR: 0.005
  WARMUP_ITERS: 10
  IMS_PER_BATCH: 16
  MAX_EPOCHS: 70
  STEPS: (20,40)

TEST:
  RE_RANKING: 'no'
  WEIGHT: ''
  NECK_FEAT: 'before'
  FEAT_NORM: 'yes'
  FEAT: 0
  CROSS: 0
  MISS: 'r2n'
OUTPUT_DIR: './RGBNT201/BASE_Keep100'



