MODEL:
  PRETRAIN_CHOICE: 'imagenet'
  RES_USE: 1
  TRANS_USE: 1
  DEPTH: 1
  MIX_DIM: 768
  PRETRAIN_PATH_R: '/15127306268/wyh/UIS/pth/r50.pth'
  PRETRAIN_PATH_T: '/15127306268/wyh/UIS/pth/vitb_16_224_21k.pth'
  TRANSFORMER_TYPE: 'vit_base_patch16_224'
  STRIDE_SIZE: [ 16, 16 ]
  SIE_CAMERA: False
  MIX_MODE: 0
  BASE: 1
  RE: 1
  NO_MARGIN: True
INPUT:
  SIZE_TRAIN: [ 384, 192 ]
  SIZE_TEST: [ 384, 192 ]
  PROB: 0.5 # random horizontal flip
  RE_PROB: 0.5 # random erasing
  PADDING: 10
DATASETS:
  NAMES: ('RegDB')
  ROOT_DIR: '/15127306268/wyh/MM/data/'
DATALOADER:
  SAMPLER: 'softmax_triplet'
  NUM_WORKERS: 14
  NUM_INSTANCE: 2
SOLVER:
  OPTIMIZER_NAME: 'SGD'
  BASE_LR: 0.009
  WARMUP_ITERS: 10
  IMS_PER_BATCH: 16
  MAX_EPOCHS: 120
  STEPS: ( 40, 70 )
TEST:
  RE_RANKING: 'no'
  WEIGHT: ''
  NECK_FEAT: 'before'
  FEAT_NORM: 'yes'
  FEAT: 0
  CROSS: 1
  MISS: "None"
  CROSS_TYPE: 'n2r'
OUTPUT_DIR: '/15127306268/wyh/MM/RegDB/Baseline_T_PCA'



