MODEL:
  PRETRAIN_CHOICE: 'imagenet'
  RES_USE : 1
  TRANS_USE : 1
  RES_MODE : 2
  SRM_LAYER : 2
  MIX_DIM : 768
  PRETRAIN_PATH_R : '/15127306268/wyh/UIS/pth/r101.pth'
  PRETRAIN_PATH_T : '/15127306268/wyh/UIS/pth/deit_base_distilled_patch16_224-df68dfff.pth'
  TRANSFORMER_TYPE: 'vit_base_patch16_224'
  STRIDE_SIZE: [12, 12]
  SIE_CAMERA: True


INPUT:
  SIZE_TRAIN: [256, 128]
  SIZE_TEST: [256, 128]
  PROB: 0.5 # random horizontal flip
  RE_PROB: 0.5 # random erasing
  PADDING: 10
  PIXEL_MEAN: [0.5, 0.5, 0.5]
  PIXEL_STD: [0.5, 0.5, 0.5]

DATASETS:
  NAMES: ('msmt17')
  ROOT_DIR: './data'

TEST:
  RE_RANKING: 'no'
  WEIGHT: ''
  NECK_FEAT: 'before'
  FEAT_NORM: 'yes'

OUTPUT_DIR: './msmt_deitb12_res101_layer2'

